name = "docbuild"
reservoir = false
version = "0.1.0"
packagesDir = "../.lake/packages"

[[require]]
name = "formal_conjectures"
path = "../"

[[require]]
scope = "leanprover"
name = "doc-gen4"
rev = "v4.21.0"

[[lean_exe]]
name = "overwrite_index"
srcDir = "scripts"
root = "overwrite_index"
exeName = "overwrite_index"
supportInterpreter = true
